### ISSUE TITLE
release latest version

### ISSUE THREAD

**Issue by kesla** [tunnckoCore/then-read-json#2]
hey,

doesn't seem the latest commit has been released to the npm registry, where you simplified and removed the `then-parse-json` dependency

**Comment by tunnckoCore** [comment]
Heya, @kesla 

Very thanks! 

_(edit: closing because #3)_

**Comment by kesla** [comment]
Hey,

So this was actually about releasing this to npm! Any chance we can get a 1.0.2 out? :)

**Comment by tunnckoCore** [comment]
@kesla thanks again! Released 1.0.2 and 1.0.3 :)

thanks using it.
